android:
  config:
    "dynatrace {
      configurations {
        defaultConfig {
          autoStart{
            applicationId 'fc826a2a-2218-4bcb-800c-f60db6358a9b'
            beaconUrl 'https://bf15243sse.bf.dynatrace.com/mbeacon'
          }
          userOptIn true
          agentBehavior.startupLoadBalancing true
        }
      }
    }"

ios:
  config:
    "<key>DTXApplicationID</key>
    <string>fc826a2a-2218-4bcb-800c-f60db6358a9b</string>
    <key>DTXBeaconURL</key>
    <string>https://bf15243sse.bf.dynatrace.com/mbeacon</string>
    <key>DTXUserOptIn</key>
    <true/>
    <key>DTXStartupLoadBalancing</key>
    <true/>"
